### ISSUE TITLE
As a user, I have a profile that I can view and edit.

### ISSUE THREAD

**Issue by KolbeML** [Cyber4All/clark-client#10]
So that...
1. ~~Other users can see Learning Objects I've created~~ See #22
2. I can view a list of Learning Objects I've downloaded
3. ~~Other users can see my name and associations~~ See #22
4. ~~I can easily find other users with the same associations as me~~ See #21
5. I can edit my profile information
6. ~~I can edit when I receive email notifications from CuBE~~ See #20 
7. ~~I can report other users who have inappropriate content in their profiles~~ See #23

**Comment by DonSeannelly** [comment]
@Jewel7 please close the issue once list item 2 and 5 are closed. Also, before merging any profile editing features into production please open a feature request in the User's API to have those features built out in the back-end.
