### ISSUE TITLE
Card layout on home page - not standard size - and change title

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#143]
The cards appear to be of different sizes based on description. I know this was fixed earlier so it's probably something small. 

Also - Please change title from "Latest..." to "Recent..." 

<img width="1189" alt="screen shot 2018-04-07 at 9 24 37 pm" src="https://user-images.githubusercontent.com/2423261/38461903-1d4019b0-3aaa-11e8-86f4-eda4bb3fc3e0.png">

**Comment by nrwinner** [comment]
The issue here is that we're truncating the text in the description to a specified character count, not the title. This is one of the longer titles and it wraps three lines. Suggest we truncate titles as well.

**Comment by siddharthkaza** [comment]
I agree. I think we should truncate titles as well. Cards being different sizes doesn’t look great.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
