### ISSUE TITLE
The user profile should prompt the user to publish a learning object

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/clark-client#144]
When the user views their profile without any published learning objects, they should be prompted to create and publish a learning object through the onion. This text should display where the learning objects would list out, and include a link.

![screen shot 2018-04-09 at 12 43 03 pm](https://user-images.githubusercontent.com/14933100/38510704-cab7938a-3bf3-11e8-968e-70e0d60cda85.png)

**Comment by nrwinner** [comment]
@Ballen2713 this is actually bug, not a new feature. There's a check somewhere in the profile code the isn't working properly but the functionality is there already.

**Comment by gshaw1997** [comment]
Closed in some unidentifiable commit
