### ISSUE TITLE
Learning Objects should display a saves counter

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/clark-client#24]
## Feature Request
Learning Objects should display a saves counter.

### Rationale
To provide a metric for which to sort Learning Objects.

**Comment by gshaw1997** [comment]
@DonSeannelly @nrwinner 
Should `cart-service` keep track of downloads and `learning-object-service (database-interaction)` ask `cart-service` for this metric or should it just be kept track of within `learning-object-service (database-interaction)`?

**Comment by DonSeannelly** [comment]
Once https://github.com/Cyber4All/learning-object-service/issues/35 is completed LOs can properly display this data in the client.

**Comment by gshaw1997** [comment]
Closed in 5f1c0ea5fbc04005eebe1e7abcc3a36550318f3b
