### ISSUE TITLE
Search bug and issue in builder - might need multiple issues

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#245]
![14b676cb-ee0b-43f7-8efd-e1ec5dfe01c9](https://user-images.githubusercontent.com/2423261/39962202-cf294f62-5615-11e8-9f05-f784bc9548c3.png)

**Comment by DonSeannelly** [comment]
1. is Resolved via Cyber4All/learning-object-service@8ec3aea
