### ISSUE TITLE
Tooltips/Help

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#28]
Add the capability to add tooltips. 
So user can click on "?" and know more. For instance, what is a learning object next to a label that mentioned learning objects.

**Comment by Jewel7** [comment]
Tooltips for searching for Learning Objects in Clark have been added. When hovering over name, the tooltip displays the length of time a learning object will take. (not yet committed to the tooltips branch, will talk with team before committing)

**Comment by tylernhoward** [comment]
Finished implementation of this feature in cube. Closing branch.

Will continue to add tooltips throughout application

**Comment by tylernhoward** [comment]
If additional tooltips are required, see [Tooltip Readme](https://github.com/Cyber4All/clark-tooltip/blob/master/README.MD)
