### ISSUE TITLE
Standard Outcomes Filter is overlayed by navbar in the CUBE 

### ISSUE THREAD

**Issue by Ballen2713** [Cyber4All/clark-client#286]
When you click the standard outcomes search filter it is overlayed by the navbar 
<img width="960" alt="picture1" src="https://user-images.githubusercontent.com/37280445/41295815-7864351c-6e29-11e8-8196-3e4279b4d9ce.PNG">
<img width="960" alt="picture2" src="https://user-images.githubusercontent.com/37280445/41295817-7ad542aa-6e29-11e8-8e14-2b7433d2a1a2.PNG">

and when you scroll down its hard to see the full text of the title

**Comment by Ballen2713** [comment]
It happens if you scroll up to view the outcome suggestions

**Comment by nrwinner** [comment]
This is actually fixed in the child-objects branch.

**Comment by Ballen2713** [comment]
@nrwinner Okay shall I just delete this issue then?
