### ISSUE TITLE
Materials should show indication of pending delete

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/clark-client#449]
When deleting a file or folder from the manage materials page, the user should be given some indication that their action is pending while the client waits for a response across the network. Some form of visual change (i.e. an indicator or animation) would signal to the user that everything is working as normal, whereas now, especially on slower connections, the user is given time to wonder if the delete is working.

**Comment by joelbutler1010** [comment]
WIP using the delete-indicator branch
