### ISSUE TITLE
Meta description of CLARK

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#477]
Change meta description to: 

CLARK is a digital library that hosts diverse cybersecurity learning objects. It was created because there is a demonstrated need for a high-quality and high-availability repository for curricular and ancillary resources in the cybersecurity education community. The curriculum in CLARK is free, resides in several collections, and undergoes stringent reviews.

**Comment by joelbutler1010** [comment]
Addressed in PR#482
