### ISSUE TITLE
Add Justine Caylor, Sagar Raina, and Kira Fallen to team page

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#565]
This will be a separate sub-group. Slack Justine to get her picture. Kira's picture is here: http://cis1.towson.edu/~cyber4all/index.php/project-team/

Justine Caylor - Lead Technical Editor
Kira Fallon - Editor (High School Intern)

Sagar in yet another group (this would be reserved for consultants) - His picture and title is here: http://cis1.towson.edu/~cyber4all/index.php/project-team/

**Comment by DonSeannelly** [comment]
For these groupings, would we like to have titles (like Editorial Team, Consultants) or still continue to only have visual separation?

**Comment by siddharthkaza** [comment]
I suggest titles now since the number of groups has become unwieldy. Please use these:
Lead Developers 
Developers 
Technical Editors
Consultants 
Past Participants

**Comment by pzalep1** [comment]
Completed and deployed.
