### ISSUE TITLE
Reviewers should be able to switch between released and revised versions of a learning object on details page

### ISSUE THREAD

**Issue by nrwinner** [Cyber4All/clark-client#572]
As a reviewer/curator/editor/admin, I want to be able to switch between the released version of a Learning Object and it's latest submission while on the details page - with a clear indication of what I am currently viewing -  so that I can quickly navigate between a submission and the released version.

Needs Cyber4All/learning-object-service#231
Needs Cyber4All/clark-client#613
Needs Cyber4All/learning-object-service#187
Needs Cyber4All/library-service#90
Needs Cyber4All/learning-object-service#291
Needs Cyber4All/CLARK-Gateway#77

**Comment by DonSeannelly** [comment]
Data Integration, endpoint test, e2e test: Size 2
