### ISSUE TITLE
UI does not load learning objects through search

### ISSUE THREAD

**Issue by tylernhoward** [Cyber4All/clark-client#594]
As seen below, when a search is made the UI seems to never update the page after receiving the response from the endpoint:
![image](https://user-images.githubusercontent.com/12202344/52158926-94b8b580-266b-11e9-9ac8-2f2a2c458e87.png)

The response looks good:
![image](https://user-images.githubusercontent.com/12202344/52158935-aa2ddf80-266b-11e9-9073-e38217471844.png)

@nrwinner honestly what are you doing

**Comment by DonSeannelly** [comment]
Closed via 982cafc
