### ISSUE TITLE
Add a Loading Spinner on Login

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/clark-client#60]
### Feature Request
When the login or register button is clicked there should be a loading spinner (or comparable UI element) to signal to the user that a request to the server has been made.

### Rationale
Currently it is not clear that anything is happening, so on slower connections the user might wrongly assume that the application has broken.

**Comment by Jewel7** [comment]
When the user clicks the "Login" or "Register" buttons, the text within the button now changes to "Loading" and has a loading spinner next to it.
