### ISSUE TITLE
Send cookie in public requests

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/clark-client#613]
On public requests the cookie is not sent up to the server. Without authorization the service can only send down public resources meaning privileged users cannot see content that requires auth privileges.

**Comment by DonSeannelly** [comment]
We should consider using [HTTP Interceptors](https://angular.io/api/common/http/HttpInterceptor) for this so that we can just tack the cookie on to every request and not have to use the `withCredentials` parameter anymore.
