### ISSUE TITLE
Two requests being made for single object in builder 

### ISSUE THREAD

**Issue by pzalep1** [Cyber4All/clark-client#616]
Resolve issue with builder firing off two requests for the same object

**Comment by gshaw1997** [comment]
@pzalep1 Does this occur when saving or retrieving the Learning Object? Is there a specific case where this happens?

**Comment by gshaw1997** [comment]
@nrwinner Any clue as to  where/why this could be happening?

**Comment by EVogel1999** [comment]
@gshaw1997 @nrwinner
This error seems to come from the object being requested in both the the learning object guard and the builder itself.  I'm not entirely sure how to go about making this one request instead of two
