### ISSUE TITLE
Remove "community" from name of collection

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#621]
Remove the third word from name of "secure coding community" collection. Too long. breaks UI. 
<img width="403" alt="screen shot 2019-02-13 at 7 50 03 pm" src="https://user-images.githubusercontent.com/2423261/52754529-da10a780-2fc8-11e9-8ada-f0299c650097.png">

**Comment by gshaw1997** [comment]
@siddharthkaza @nrwinner Could we just truncate and ellipses instead of renaming the collection?

**Comment by siddharthkaza** [comment]
Yes. That should be fine. As long as it fits the yello flag on the cards.
