### ISSUE TITLE
Builder Does Not Respond to Service Errors

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/clark-client#677]
When the Learning Object Service responds with a 500 error, the builder does not communicate the failure to the user. From the user perspective, everything is working and they should keep going. This should be fixed to better communicate what is going on to our users.

**Comment by gshaw1997** [comment]
@DonSeannelly  @nrwinner  @nvisal1 The plan of action we decided on for this issue was to retry the request a few times and after consecutive service failures, displaying a modal conveying to the user that their work cannot be saved at this time and routing them out of the builder. Is this correct?

**Comment by nrwinner** [comment]
@gshaw1997 Yep that was our plan
