### ISSUE TITLE
Need a tooltip next to Learning Object

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#71]
in the "new learning object" screen. 

"A Learning Object is a Course, Unit, Module, Micro-module or a nano-module to teach content online or in-class"

**Comment by tylernhoward** [comment]
@siddharthkaza Do we prefer  
A. "A Learning Object isa shareable, self-contained piece of curriculum that has clearly identified learning outcomes, assessment strategies, and instructional strategies"
B. "A Learning Object is a Course, Unit, Module, Micro-module or a nano-module to teach content online or in-class"

**Comment by siddharthkaza** [comment]
Prefer number #1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
