### ISSUE TITLE
Make the Filters Panel More Prominent

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/clark-client#728]
The filters side-panel should be updated to make it easier for a user to distinguish that these are filters. Perhaps a bounding box of some sort, and making the title more pronounced? 

![image](https://user-images.githubusercontent.com/14933100/54371295-863cc100-464f-11e9-9f17-729067ca7fbe.png)

**Comment by EVogel1999** [comment]
Would it be appropriate or sufficient to wrap this in a white box that is similar and consistent with the other white boxes that are around the site (i.e. object cards, results box, etc.)?
