### ISSUE TITLE
Author notifications 

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#752]
As an author, I will receive a quarterly notification with statistics on my LOs. How many downloads and any ratings.

**Comment by pzalep1** [comment]
<img width="645" alt="Screen Shot 2019-04-08 at 11 48 50 AM" src="https://user-images.githubusercontent.com/43140629/55738041-52597f00-59f4-11e9-9013-8a3c4f0ff4d1.png">

**Comment by pzalep1** [comment]
<img width="494" alt="Screen Shot 2019-04-12 at 2 51 35 PM" src="https://user-images.githubusercontent.com/43140629/56059639-7f7a9a00-5d32-11e9-9e75-a9f415fa3f48.png">
