### ISSUE TITLE
Change in tutorial text

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-client#757]
<img width="833" alt="Screen Shot 2019-03-25 at 3 48 18 PM" src="https://user-images.githubusercontent.com/2423261/54949554-bcaef180-4f15-11e9-9c76-31e5fcf8500b.png">

Remove "view in cube"
Scan the whole tutorial to remove references of "cube" and change to "search results" or something similar.

**Comment by EVogel1999** [comment]
Tutorial is now updated.
