### ISSUE TITLE
Curator dashboard not shown if also a reviewer

### ISSUE THREAD

**Issue by EVogel1999** [Cyber4All/clark-client#764]
If reviewer access groups is included with curator access groups then the curator dashboard is inaccessible.

**Comment by nrwinner** [comment]
Should a user ever be both a curator of a collection and a reviewer for a collection in the CLARK system?

**Comment by DonSeannelly** [comment]
@EVogel1999 @nrwinner this seems like a data integrity issue with the service. The user should not be both roles at the same time.
