### ISSUE TITLE
Update API Routes to Outcome Service

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/clark-client#82]
Outcome service routes need to be updated to 
`/outcomes` -  Outcome Search
`/outcomes/suggest` - Outcome Suggestion

both routes take a query with parameters
* text : `string`
* name: `string`
* author: `string`
* date: `string`
* limit: `number`
* page: `number`

**Comment by nrwinner** [comment]
Closed by 0ec4bb694cf1f4b618ff24425b4f1f5d227e8714
